const express = require("express");
const cors = require("cors");

const app=express();
app.use(cors());

app.get('/movies/categories',(req,res) => {
    
    res.json(["animation", "mystery", "comedy", "classic"])
   
})

app.get('/movies/category/animation',(req,res) => {
    setTimeout(() =>{
    res.json(
        [{"id":1,"category":"animation", "title":"Inside Out","posterURL":"https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg","imdbId":"tt2096673"},{"id":2,"category":"animation", "title":"Coco","posterURL":"https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg","imdbId":"tt2380307"},{"id":3,"category":"animation", "title":"Incredibles 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg","imdbId":"tt3606756"},{"id":4,"category":"animation", "title":"Snow White and the Seven Dwarfs","posterURL":"https://m.media-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_SX300.jpg","imdbId":"tt0029583"},{"id":5,"category":"animation", "title":"Zootopia","posterURL":"https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_SX300.jpg","imdbId":"tt2948356"},{"id":6,"category":"animation", "title":"Toy Story 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0120363"},{"id":7,"category":"animation", "title":"Up","posterURL":"https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg","imdbId":"tt1049413"},{"id":8,"category":"animation", "title":"Toy Story 3","posterURL":"https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg","imdbId":"tt0435761"},{"id":9,"category":"animation", "title":"Finding Nemo","posterURL":"https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt0266543"},{"id":10,"category":"animation", "title":"Finding Dory","posterURL":"https://m.media-amazon.com/images/M/MV5BNzg4MjM2NDQ4MV5BMl5BanBnXkFtZTgwMzk3MTgyODE@._V1_SX300.jpg","imdbId":"tt2277860"}]
    )
},300)
})





app.get('/movies/category/comedy',(req,res) => {
    setTimeout(() =>{
        res.json(
            [{"id":11,"category":"comedy", "title":"Zootopia","posterURL":"https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_SX300.jpg","imdbId":"tt2948356"},{"id":12,"category":"comedy", "title":"The Philadelphia Story","posterURL":"https://m.media-amazon.com/images/M/MV5BYjQ4ZDA4NGMtMTkwYi00NThiLThhZDUtZTEzNTAxOWYyY2E4XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_SX300.jpg","imdbId":"tt0032904"},{"id":13,"category":"comedy", "title":"Toy Story 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0120363"},{"id":14,"category":"comedy", "title":"Up","posterURL":"https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg","imdbId":"tt1049413"},{"id":15,"category":"comedy", "title":"Toy Story 3","posterURL":"https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg","imdbId":"tt0435761"},{"id":16,"category":"comedy", "title":"Finding Nemo","posterURL":"https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt0266543"},{"id":17,"category":"comedy", "title":"Three Billboards Outside Ebbing, Missouri","posterURL":"https://m.media-amazon.com/images/M/MV5BMjMxNzgwMDUyMl5BMl5BanBnXkFtZTgwMTQ0NTIyNDM@._V1_SX300.jpg","imdbId":"tt5027774"},{"id":18,"category":"comedy", "title":"Kind Hearts and Coronets","posterURL":"https://m.media-amazon.com/images/M/MV5BNjI5N2Y4YWEtYThmOC00ODA0LTlhMGYtNmE3MmVmNjNhYWQyXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0041546"},{"id":19,"category":"comedy", "title":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","posterURL":"https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","imdbId":"tt0057012"},{"id":20,"category":"comedy", "title":"The Death of Stalin: Dictators, Murderers and Comrades... Oh My!","posterURL":"https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg","imdbId":"tt9019280"}]
        )
},600)
})



app.get('/movies/category/classic',(req,res) => {
    setTimeout(() =>{
    res.json(
    [{"id":21,"category":"classic", "title":"All Quiet on the Western Front","posterURL":"https://m.media-amazon.com/images/M/MV5BMzg2MWQ4MDEtOGZlNi00MTg0LWIwMjQtYWY5NTQwYmUzMWNmXkEyXkFqcGdeQXVyMzg2MzE2OTE@._V1_SX300.jpg","imdbId":"tt0020629"},{"id":22,"category":"classic", "title":"Vertigo","posterURL":"https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0052357"},{"id":23,"category":"classic", "title":"Rebecca","posterURL":"https://m.media-amazon.com/images/M/MV5BYTcxYWExOTMtMWFmYy00ZjgzLWI0YjktNWEzYzJkZTg0NDdmL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0032976"},{"id":24,"category":"classic", "title":"The Treasure of the Sierra Madre","posterURL":"https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkMS00ODE0LThlM2ItMDI3NGQ2YjhmMzkxXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0040897"},{"id":25,"category":"classic", "title":"Lawrence of Arabia","posterURL":"https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0056172"},{"id":26,"category":"classic", "title":"The Big Sleep","posterURL":"https://m.media-amazon.com/images/M/MV5BMjdiM2IyZmQtODJiYy00NDNkLTllYmItMmFjMDNiYTQyOGVkXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","imdbId":"tt0038355"},{"id":27,"category":"classic", "title":"Frankenstein","posterURL":"https://m.media-amazon.com/images/M/MV5BN2RjNjU4MmUtZWU5MS00MjdhLTkxM2MtYjBiM2FhYTE4OTQwXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0021884"},{"id":28,"category":"classic", "title":"A Streetcar Named Desire","posterURL":"https://m.media-amazon.com/images/M/MV5BNzk2M2Y3MzYtNGMzMi00Y2FjLTkwODQtNmExYWU3ZWY3NzExXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","imdbId":"tt0044081"},{"id":29,"category":"classic", "title":"Kind Hearts and Coronets","posterURL":"https://m.media-amazon.com/images/M/MV5BNjI5N2Y4YWEtYThmOC00ODA0LTlhMGYtNmE3MmVmNjNhYWQyXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0041546"},{"id":30,"category":"classic", "title":"Chinatown","posterURL":"https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg","imdbId":"tt0071315"}]
    )
},700)
})


app.get('/movies/category/mystery',(req,res) => {
    setTimeout(() =>{
        res.json(
            [{"id":31,"category":"mystery", "title":"The Lady Vanishes","posterURL":"https://m.media-amazon.com/images/M/MV5BNjk3YzFjYTktOGY0ZS00Y2EwLTk2NTctYTI1Nzc2OWNiN2I4XkEyXkFqcGdeQXVyNzM0MTUwNTY@._V1_SX300.jpg","imdbId":"tt0030341"},{"id":32,"category":"mystery", "title":"Skyfall","posterURL":"https://m.media-amazon.com/images/M/MV5BNDVhZmJiYWMtNmIzMC00ZWNiLTkzZDYtNGNlZmViMGM4OGExXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg","imdbId":"tt1074638"},{"id":33,"category":"mystery", "title":"High Noon","posterURL":"https://m.media-amazon.com/images/M/MV5BOWIzZGUxZmItOThkMS00Y2QxLTg0MTYtMDdhMjRlNTNlYTI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0044706"},{"id":34,"category":"mystery", "title":"The Godfather: Part II","posterURL":"https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","imdbId":"tt0071562"},{"id":35,"category":"mystery", "title":"Anatomy of a Murder","posterURL":"https://m.media-amazon.com/images/M/MV5BMzM0MzE2ZTAtZTBjZS00MTk5LTg5OTEtNjNmYmQ5NzU2OTUyXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","imdbId":"tt0052561"},{"id":36,"category":"mystery", "title":"Strangers on a Train","posterURL":"https://m.media-amazon.com/images/M/MV5BMjdiM2IyZmQtODJiYy00NDNkLTllYmItMmFjMDNiYTQyOGVkXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","imdbId":"tt0044079"},{"id":37,"category":"mystery", "title":"Nightcrawler","posterURL":"https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt2872718"},{"id":38,"category":"mystery", "title":"Invasion of the Body Snatchers","posterURL":"https://m.media-amazon.com/images/M/MV5BYTExYjM3MDYtMzg4MC00MjU4LTljZjAtYzdlMTFmYTJmYTE4XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg","imdbId":"tt0049366"},{"id":39,"category":"mystery", "title":"The Post: The Style Section - Re-Creating an Era","posterURL":"https://m.media-amazon.com/images/M/MV5BNjg5YTE4ODUtZDVkZi00YmRiLWIwZTMtOTRiMjQ3NDg3ZTQ4XkEyXkFqcGdeQXVyMjQ5NjgwMjA@._V1_SX300.jpg","imdbId":"tt8641788"},{"id":40,"category":"mystery", "title":"Freaks","posterURL":"https://m.media-amazon.com/images/M/MV5BMjMyYjgyOTQtZDVlZS00NTQ0LWJiNDItNGRlZmM3Yzc0N2Y0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","imdbId":"tt0022913"}]
        )
},500)
})


const movies=[{"id":1,"category":"animation", "title":"Inside Out","posterURL":"https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg","imdbId":"tt2096673"},{"id":2, "category":"animation", "title":"Coco","posterURL":"https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg","imdbId":"tt2380307"},{"id":3,"category":"animation", "title":"Incredibles 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg","imdbId":"tt3606756"},{"id":4, "category":"animation", "title":"Snow White and the Seven Dwarfs","posterURL":"https://m.media-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_SX300.jpg","imdbId":"tt0029583"},{"id":5,"category":"animation", "title":"Zootopia","posterURL":"https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_SX300.jpg","imdbId":"tt2948356"},{"id":6,"category":"animation", "title":"Toy Story 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0120363"},{"id":7,"category":"animation", "title":"Up","posterURL":"https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg","imdbId":"tt1049413"},{"id":8,"category":"animation", "title":"Toy Story 3","posterURL":"https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg","imdbId":"tt0435761"},{"id":9,"category":"animation", "title":"Finding Nemo","posterURL":"https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt0266543"},{"id":10,"category":"animation", "title":"Finding Dory","posterURL":"https://m.media-amazon.com/images/M/MV5BNzg4MjM2NDQ4MV5BMl5BanBnXkFtZTgwMzk3MTgyODE@._V1_SX300.jpg","imdbId":"tt2277860"},
                {"id":11,"category":"comedy", "title":"Zootopia","posterURL":"https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_SX300.jpg","imdbId":"tt2948356"},{"id":12, "category":"comedy", "title":"The Philadelphia Story","posterURL":"https://m.media-amazon.com/images/M/MV5BYjQ4ZDA4NGMtMTkwYi00NThiLThhZDUtZTEzNTAxOWYyY2E4XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_SX300.jpg","imdbId":"tt0032904"},{"id":13,"category":"comedy", "title":"Toy Story 2","posterURL":"https://m.media-amazon.com/images/M/MV5BMWM5ZDcxMTYtNTEyNS00MDRkLWI3YTItNThmMGExMWY4NDIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0120363"},{"id":14,"category":"comedy", "title":"Up","posterURL":"https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg","imdbId":"tt1049413"},{"id":15,"category":"comedy", "title":"Toy Story 3","posterURL":"https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg","imdbId":"tt0435761"},{"id":16,"category":"comedy", "title":"Finding Nemo","posterURL":"https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt0266543"},{"id":17,"category":"comedy", "title":"Three Billboards Outside Ebbing, Missouri","posterURL":"https://m.media-amazon.com/images/M/MV5BMjMxNzgwMDUyMl5BMl5BanBnXkFtZTgwMTQ0NTIyNDM@._V1_SX300.jpg","imdbId":"tt5027774"},{"id":18,"category":"comedy", "title":"Kind Hearts and Coronets","posterURL":"https://m.media-amazon.com/images/M/MV5BNjI5N2Y4YWEtYThmOC00ODA0LTlhMGYtNmE3MmVmNjNhYWQyXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0041546"},{"id":19,"category":"comedy", "title":"Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","posterURL":"https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","imdbId":"tt0057012"},{"id":20,"category":"comedy", "title":"The Death of Stalin: Dictators, Murderers and Comrades... Oh My!","posterURL":"N/A","imdbId":"tt9019280"},
                {"id":21,"category":"classic", "title":"All Quiet on the Western Front","posterURL":"https://m.media-amazon.com/images/M/MV5BMzg2MWQ4MDEtOGZlNi00MTg0LWIwMjQtYWY5NTQwYmUzMWNmXkEyXkFqcGdeQXVyMzg2MzE2OTE@._V1_SX300.jpg","imdbId":"tt0020629"},{"id":22,"category":"classic", "title":"Vertigo","posterURL":"https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0052357"},{"id":23,"category":"classic", "title":"Rebecca","posterURL":"https://m.media-amazon.com/images/M/MV5BYTcxYWExOTMtMWFmYy00ZjgzLWI0YjktNWEzYzJkZTg0NDdmL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0032976"},{"id":24,"category":"classic", "title":"The Treasure of the Sierra Madre","posterURL":"https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkMS00ODE0LThlM2ItMDI3NGQ2YjhmMzkxXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0040897"},{"id":25,"category":"classic", "title":"Lawrence of Arabia","posterURL":"https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg","imdbId":"tt0056172"},{"id":26,"category":"classic", "title":"The Big Sleep","posterURL":"https://m.media-amazon.com/images/M/MV5BMjdiM2IyZmQtODJiYy00NDNkLTllYmItMmFjMDNiYTQyOGVkXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","imdbId":"tt0038355"},{"id":27,"category":"classic", "title":"Frankenstein","posterURL":"https://m.media-amazon.com/images/M/MV5BN2RjNjU4MmUtZWU5MS00MjdhLTkxM2MtYjBiM2FhYTE4OTQwXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0021884"},{"id":28,"category":"classic", "title":"A Streetcar Named Desire","posterURL":"https://m.media-amazon.com/images/M/MV5BNzk2M2Y3MzYtNGMzMi00Y2FjLTkwODQtNmExYWU3ZWY3NzExXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","imdbId":"tt0044081"},{"id":29,"category":"classic", "title":"Kind Hearts and Coronets","posterURL":"https://m.media-amazon.com/images/M/MV5BNjI5N2Y4YWEtYThmOC00ODA0LTlhMGYtNmE3MmVmNjNhYWQyXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg","imdbId":"tt0041546"},{"id":30,"category":"classic", "title":"Chinatown","posterURL":"https://m.media-amazon.com/images/M/MV5BOGMwYmY5ZmEtMzY1Yi00OWJiLTk1Y2MtMzI2MjBhYmZkNTQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","imdbId":"tt0071315"},
                {"id":31,"category":"mystery", "title":"The Lady Vanishes","posterURL":"https://m.media-amazon.com/images/M/MV5BNjk3YzFjYTktOGY0ZS00Y2EwLTk2NTctYTI1Nzc2OWNiN2I4XkEyXkFqcGdeQXVyNzM0MTUwNTY@._V1_SX300.jpg","imdbId":"tt0030341"},{"id":32,"category":"mystery", "title":"Skyfall","posterURL":"https://m.media-amazon.com/images/M/MV5BNDVhZmJiYWMtNmIzMC00ZWNiLTkzZDYtNGNlZmViMGM4OGExXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg","imdbId":"tt1074638"},{"id":33,"category":"mystery", "title":"High Noon","posterURL":"https://m.media-amazon.com/images/M/MV5BOWIzZGUxZmItOThkMS00Y2QxLTg0MTYtMDdhMjRlNTNlYTI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0044706"},{"id":34,"category":"mystery", "title":"The Godfather: Part II","posterURL":"https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","imdbId":"tt0071562"},{"id":35,"category":"mystery", "title":"Anatomy of a Murder","posterURL":"https://m.media-amazon.com/images/M/MV5BMzM0MzE2ZTAtZTBjZS00MTk5LTg5OTEtNjNmYmQ5NzU2OTUyXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg","imdbId":"tt0052561"},{"id":36,"category":"mystery", "title":"Strangers on a Train","posterURL":"https://m.media-amazon.com/images/M/MV5BNzc5N2ZjNWMtNWVkZi00MzYyLTkxNjYtMzc0NjE0MDFjNGQ0XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","imdbId":"tt0044079"},{"id":37,"category":"mystery", "title":"Nightcrawler","posterURL":"https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","imdbId":"tt2872718"},{"id":38,"category":"mystery", "title":"Invasion of the Body Snatchers","posterURL":"https://m.media-amazon.com/images/M/MV5BYTExYjM3MDYtMzg4MC00MjU4LTljZjAtYzdlMTFmYTJmYTE4XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg","imdbId":"tt0049366"},{"id":39,"category":"mystery", "title":"The Post: The Style Section - Re-Creating an Era","posterURL":"https://m.media-amazon.com/images/M/MV5BNjg5YTE4ODUtZDVkZi00YmRiLWIwZTMtOTRiMjQ3NDg3ZTQ4XkEyXkFqcGdeQXVyMjQ5NjgwMjA@._V1_SX300.jpg","imdbId":"tt8641788"},{"id":40,"category":"mystery", "title":"Freaks","posterURL":"https://m.media-amazon.com/images/M/MV5BMjMyYjgyOTQtZDVlZS00NTQ0LWJiNDItNGRlZmM3Yzc0N2Y0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","imdbId":"tt0022913"}];
        
app.get('/movie/:id',(req,res) => {
    setTimeout(() =>{
        // var id = +req.params.id; // will contains data from :id, the + is to parse string to integer
        // var movie = movies.find(u => u.id === id); // find movie from movies using .find method
        const id= parseInt(req.params.id);
        const movie = movies.find(u => u.id === id);
        if(!movie){
            res.status(404).json({error:"Data not found"});
        }else{
            res.json(movie); // send the data
        }
},500)
})

app.listen(3300,() =>{
    console.log("server started on Port 3300 !")
});